language: ruby
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.config
  - $HOME/.cache/pip
before_install:
- pip install --user awscli
script:
- wget https://raw.githubusercontent.com/szmolin/dist/master/set-mod-time -O $HOME/set-mod-time
- chmod +x $HOME/set-mod-time
- $HOME/set-mod-time -config=$HOME/.config/config.txt
- find . \( -iname '*.html' -o -iname '*.css' -o -iname '*.js' \) -exec gzip -9 -n \
  {} \; -exec mv {}.gz {} \;
- env AWS_ACCESS_KEY_ID=${SG_AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${SG_AWS_SECRET_ACCESS_KEY} \
  aws --region ap-southeast-1 s3 sync . s3://${BUCKET}/wow/ --delete --exclude '*' \
  --include '*.css' --include '*.js' --include '*.html' --cache-control 'max-age=7200' \
  --content-encoding gzip --delete
- env AWS_ACCESS_KEY_ID=${SG_AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${SG_AWS_SECRET_ACCESS_KEY} \
  aws --region ap-southeast-1 s3 sync . s3://${BUCKET}/wow/ --delete --exclude ".travis.yml" \
  --exclude ".git/*" --exclude "README.md" --exclude '*.css' --exclude '*.js' --exclude \
  '*.html'
- aws --region cn-north-1 s3 sync . s3://${BUCKET}/wow/ --delete --exclude '*' --include \
  '*.css' --include '*.js' --include '*.html' --cache-control 'max-age=7200' --content-encoding \
  gzip --delete --page-size 50
- aws --region cn-north-1 s3 sync . s3://${BUCKET}/wow/ --delete --exclude ".travis.yml" \
  --page-size 50 --exclude ".git/*" --exclude "README.md" --exclude '*.css' --exclude \
  '*.js' --exclude '*.html'
env:
  global:
    secure: do+pZqJ8gzeUPiDNsId1sqiqqJ+Bf4l+G+Ir07ujhHi1OP+Udc15IujX5L5xOzlk396ijFQXSoicM7c473LQQXRuDyygj7pkGFyfG2SGBzFn+7by/s8YpKLWsHr9xfuwwiwXq11FgTYoMfZvUI4fEp3YEQCjMmgu2PegkzHFp6zlS2Wm8N/bq+e3LxiXGHazrXNV5vEO6R3oz7CQeGEYTNVcSb0A8Pf2A0gDbHr/VRba/CMaMclcX/7w71oh845J04pEOjoMXLPNud8EfDgxoa7rpPj5s2rM9mgfxw02+Ss5MSA/JTyrSYr7gaSMJO5eR4pOvEBfyL59qPfrzhMwtu1UsjAK6vMhddDfY3LidbGIoCML9V6z0DBISAEfTyJJzgoWCmbfg4mZRJ50pPz5y0NkCRwAIms2DgcHYmf8SY9xy9JeXGYBYq5Dl/6DPTVwBozCG3UPw0VJqA4yTP2Ro/vJh0r2B6m4PgDCTlYSxuJesONzX0tHYKlWviGP3AKDMGjYSvZB4CHHPrzGGIQGpJ3ww1gJUbZ/hvLwwbk/35cmu4Piv3JhS54GiViXekYQBXTV+HpqvmItXbhv8ksViZwreKih2XsJzHmTYDh5EkZe7y03+jED9JW9hhVl8jl/FMgyh8EhgfsAvDZzrrcpHnDPeNiqsh27TjG22HczwaA=
